create table team
(
    id varchar(10),
    name varchar(30),
    nationality varchar(20),
    group_number varchar(15),
    primary key (id)
);

insert into team (id, nationality, name, group_number)
values  ('T-03', 'Argentina', 'ARG', 'Group D'),
        ('T-04', 'Australia', 'AUS', 'Group C'),
        ('T-06', 'Belgium', 'BEL', 'Group G'),
        ('T-09', 'Brazil', 'BRA', 'Group E'),
        ('T-15', 'Colombia', 'COL', 'Group H'),
        ('T-16', 'Costa Rica', 'CRI', 'Group E'),
        ('T-17', 'Croatia', 'HRV', 'Group D'),
        ('T-21', 'Denmark', 'DNK', 'Group C'),
        ('T-25', 'Egypt', 'EGY', 'Group A'),
        ('T-27', 'England', 'ENG', 'Group G'),
        ('T-28', 'France', 'FRA', 'Group C'),
        ('T-29', 'Germany', 'DEU', 'Group F'),
        ('T-35', 'Iceland', 'ISL', 'Group D'),
        ('T-36', 'Iran', 'IRN', 'Group B'),
        ('T-42', 'Japan', 'JPN', 'Group H'),
        ('T-44', 'Mexico', 'MEX', 'Group F'),
        ('T-45', 'Morocco', 'MAR', 'Group B'),
        ('T-48', 'Nigeria', 'NGA', 'Group D'),
        ('T-52', 'Panama', 'PAN', 'Group G'),
        ('T-54', 'Peru', 'PER', 'Group C'),
        ('T-55', 'Poland', 'POL', 'Group H'),
        ('T-56', 'Portugal', 'PRT', 'Group B'),
        ('T-59', 'Russia', 'RUS', 'Group A'),
        ('T-60', 'Saudi Arabia', 'SAU', 'Group A'),
        ('T-62', 'Senegal', 'SEN', 'Group H'),
        ('T-63', 'Serbia', 'SRB', 'Group E'),
        ('T-68', 'South Korea', 'KOR', 'Group F'),
        ('T-70', 'Spain', 'ESP', 'Group B'),
        ('T-71', 'Sweden', 'SWE', 'Group F'),
        ('T-72', 'Switzerland', 'CHE', 'Group E'),
        ('T-75', 'Tunisia', 'TUN', 'Group G'),
        ('T-80', 'Uruguay', 'URY', 'Group A');